import type { ClinicPrintInfo } from '@/services/clinic.service';

interface ClinicPrintHeaderProps {
  clinic?: ClinicPrintInfo | null;
  /** Shown on the right side of the header (e.g. Rx No / Invoice No) */
  rightSlot?: React.ReactNode;
}

/**
 * Shared print header used by all print views.
 * Shows: logo, printHeader tagline, clinic name, address, contact, GSTIN.
 */
export const ClinicPrintHeader = ({ clinic, rightSlot }: ClinicPrintHeaderProps) => {
  const addr = clinic?.address;
  const addrLine = addr
    ? [addr.line1, addr.line2, `${addr.city}, ${addr.state} – ${addr.pincode}`]
        .filter(Boolean).join(', ')
    : null;

  return (
    <div className="border-b-2 border-gray-800 pb-3 mb-4">
      <div className="flex justify-between items-start gap-4">
        {/* Left: logo + name + address */}
        <div className="flex items-start gap-3">
          {clinic?.logoUrl && (
            <img
              src={clinic.logoUrl}
              alt="Clinic logo"
              className="h-14 w-14 object-contain shrink-0"
            />
          )}
          <div>
            {clinic?.settings?.printHeader && (
              <p className="text-xs text-gray-500 mb-0.5">{clinic.settings.printHeader}</p>
            )}
            <h1 className="text-xl font-bold text-gray-900 leading-tight">
              {clinic?.name ?? 'Clinic'}
            </h1>
            {clinic?.type && (
              <p className="text-xs text-gray-500">{clinic.type}</p>
            )}
            {addrLine && (
              <p className="text-xs text-gray-500 mt-0.5 max-w-xs">{addrLine}</p>
            )}
            <div className="flex flex-wrap gap-x-3 text-xs text-gray-500 mt-0.5">
              {clinic?.mobile  && <span>☎ {clinic.mobile}</span>}
              {clinic?.email   && <span>✉ {clinic.email}</span>}
              {clinic?.website && <span>🌐 {clinic.website}</span>}
            </div>
            {(clinic?.gstin || clinic?.registrationNumber) && (
              <div className="flex gap-4 text-xs text-gray-500 mt-0.5">
                {clinic.gstin               && <span>GSTIN: {clinic.gstin}</span>}
                {clinic.registrationNumber  && <span>Reg: {clinic.registrationNumber}</span>}
              </div>
            )}
          </div>
        </div>

        {/* Right: document-specific info */}
        {rightSlot && (
          <div className="text-right text-xs text-gray-600 space-y-0.5 shrink-0">
            {rightSlot}
          </div>
        )}
      </div>
    </div>
  );
};

/** Shared print footer — shows printFooter text if set */
export const ClinicPrintFooter = ({
  clinic,
  leftSlot,
  rightSlot,
}: {
  clinic?: ClinicPrintInfo | null;
  leftSlot?: React.ReactNode;
  rightSlot?: React.ReactNode;
}) => (
  <div className="mt-6 pt-3 border-t border-gray-200 text-xs text-gray-400">
    {clinic?.settings?.printFooter && (
      <p className="text-center mb-2 text-gray-500 italic">{clinic.settings.printFooter}</p>
    )}
    <div className="flex justify-between">
      <span>{leftSlot ?? `Generated by ${clinic?.name ?? 'Clinic'}`}</span>
      {rightSlot && <span>{rightSlot}</span>}
    </div>
  </div>
);
